language: python
jdk:
  - oraclejdk8
python:
  - "3.5"
  - "3.6"
install:
  - pip install Cython
  - pip install pyjnius
  - pip install pytest
cache:
  directories:
  - $HOME/virtualenv/python3.6.3/.jip
script:
  - python -m pytest tests/dictionary_test.py
  - python -m pytest tests/parser_test.py
  - python -m pytest tests/segment_test.py
  - python -m pytest tests/tagger_test.py